---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tgtubenoti

data:

  DEBUG: "{{ $.Values.DEBUG }}"

  YamlConfigPath: "{{ $.Values.YamlConfigPath }}"

  KvToken: "{{ $.Values.KvToken }}"
  KvAccountId: "{{ $.Values.KvAccountId }}"
  KvNamespaceId: "{{ $.Values.KvNamespaceId }}"

  TgToken: "{{ $.Values.TgToken }}"
  TgChatId: "{{ $.Values.TgChatId }}"

  YtKey: "{{ $.Values.YtKey }}"
  YtChannelId: "{{ $.Values.YtChannelId }}"
  YtPublishedAfter: "{{ $.Values.YtPublishedAfter }}"


