---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-tgtubenoti

data:

  DEBUG: "{{ $.Values.DEBUG }}"

  YssUrl: "{{ $.Values.YssUrl }}"
  YssName: "{{ $.Values.YssName }}"

  TgToken: "{{ $.Values.TgToken }}"
  TgChatId: "{{ $.Values.TgChatId }}"

  YtKey: "{{ $.Values.YtKey }}"
  YtChannelId: "{{ $.Values.YtChannelId }}"
  YtPublishedAfter: "{{ $.Values.YtPublishedAfter }}"


