---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}

spec:

  selector:
    matchLabels:
      app: {{ $.Release.Name }}

  template:
    metadata:
      name: {{ $.Release.Name }}
      labels:
        app: {{ $.Release.Name }}
      annotations:
        checksum/configmap: {{ include ( print $.Template.BasePath "/" "configmap.yaml" ) . | sha256sum }}

    spec:

      containers:

        - name: {{ $.Release.Name }}
          image: "{{ $.Values.ImageNameGithubTgTubeNoti }}:{{ $.Values.ImageTagGithubTgTubeNoti }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ $.Release.Name }}

