---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}-tgtubenoti
  labels:
    app: {{ $.Release.Name }}-tgtubenoti
spec:
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-tgtubenoti
  template:
    metadata:
      name: {{ $.Release.Name }}-tgtubenoti
      labels:
        app: {{ $.Release.Name }}-tgtubenoti
    spec:
      containers:
        - name: {{ $.Release.Name }}-tgtubenoti
          imagePullPolicy: IfNotPresent
          image: "{{ $.Values.ImageNameTgTubeNoti }}:{{ $.Values.ImageTagTgTubeNoti }}"
          envFrom:
            - configMapRef:
                name: {{ $.Release.Name }}-tgtubenoti

