---

DEBUG: false

YssUrl: https://yss
YssName: tgtubenoti

TgToken: ""
TgChatId: ""

YtKey: ""
YtChannelId: ""
YtPublishedAfter: ""

ImageNameTgTubeNoti: ghcr.io/shoce/tgtubenoti
ImageTagTgTubeNoti: ""


